### Get all Posts request
GET http://localhost:5001/posts/

### Create a Post request
POST http://localhost:5001/post/
Content-Type: application/json

{
  "Title": "Hilo from the other wordoo",
  "Body": "content"
}

### Trigger Custom no MediatR notification handlers : First Approach
GET http://localhost:5001/v1/notification
    
### Trigger Custom no MediatR notification handlers : Second Approach
GET http://localhost:5001/notification