### Get all Posts request
GET http://localhost:5000/posts/

### Create a Post request
POST http://localhost:5000/post/
Content-Type: application/json

{
  "Title": "Hilo from the other wordoo",
  "Body": "content"
}

### Trigger MediatR notification handlers
GET http://localhost:5000/notification